version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: NAME_DB
      MYSQL_USER: USER_DB
      MYSQL_PASSWORD: PASSWORD_DB
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: